= amq6-persistent

Application template for ActiveMQ brokers using persistent storage.

toc::[levels=2]

== Parameters

Templates allow you to define parameters which take on a value. That value is then substituted wherever the parameter is referenced.
References can be defined in any text field in the objects list field. Refer to the
https://docs.openshift.org/latest/architecture/core_concepts/templates.html#parameters[Openshift documentation] for more information.

|=======================================================================
|Variable name |Image Environment Variable |Description |Example value

| `AMQ_RELEASE`  |  --  |  `ActiveMQ Release version, e.g. 6.2, etc.`  |  `6.2` 
| `APPLICATION_NAME`  |  --  |  `The name for the application.`  |  `broker` 
| `MQ_PROTOCOL`  |  `AMQ_PROTOCOLS`  |  `Protocol to configure.  Only openwire is supported by EAP.  amqp, amqp+ssl, mqtt, stomp, stomp+ssl, and ssl are not supported by EAP`  |  `openwire` 
| `MQ_QUEUES`  |  `AMQ_QUEUES`  |  `Queue names`  |  `${MQ_QUEUES}` 
| `MQ_TOPICS`  |  `AMQ_TOPICS`  |  `Topic names`  |  `${MQ_TOPICS}` 
| `VOLUME_CAPACITY`  |  --  |  `Size of persistent storage for database volume.`  |  `512Mi` 
| `MQ_USERNAME`  |  `AMQ_USER`  |  `Broker user name`  |  `${MQ_USERNAME}` 
| `MQ_PASSWORD`  |  `AMQ_PASSWORD`  |  `Broker user password`  |  `${MQ_PASSWORD}` 
| `AMQ_ADMIN_USERNAME`  |  `AMQ_ADMIN_USERNAME`  |  `ActiveMQ Admin User`  |  `${AMQ_ADMIN_USERNAME}` 
| `AMQ_ADMIN_PASSWORD`  |  `AMQ_ADMIN_PASSWORD`  |  `ActiveMQ Admin Password`  |  `${AMQ_ADMIN_PASSWORD}` 
| `AMQ_SECRET`  |  --  |  `Name of a secret containing SSL related files`  |  `amq-app-secret` 
| `AMQ_TRUSTSTORE`  |  `AMQ_TRUSTSTORE`  |  `SSL trust store filename`  |  `broker.ts` 
| `AMQ_KEYSTORE`  |  `AMQ_KEYSTORE_TRUSTSTORE_DIR`  |  `SSL key store filename`  |  `broker.ks` 
| `IMAGE_STREAM_NAMESPACE`  |  --  |  `Namespace in which the ImageStreams for Red Hat Middleware images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.`  |  `openshift` 
|=======================================================================

== Objects

The CLI supports various object types. A list of these object types as well as their abbreviations
can be found in the https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html#object-types[Openshift documentation].

=== Services

A service is an abstraction which defines a logical set of pods and a policy by which to access them. Refer to the
https://cloud.google.com/container-engine/docs/services/[container-engine documentation] for more information.

|=============
|Service        |Port  | Description

| `${APPLICATION_NAME}-amq-amqp`  |  `5672`  |  `The broker's amqp port.` 
| `${APPLICATION_NAME}-amq-amqp-ssl`  |  `5671`  |  `The broker's amqp ssl port.` 
| `${APPLICATION_NAME}-amq-mqtt`  |  `1883`  |  `The broker's mqtt port.` 
| `${APPLICATION_NAME}-amq-stomp`  |  `61613`  |  `The broker's stomp port.` 
| `${APPLICATION_NAME}-amq-stomp-ssl`  |  `61612`  |  `The broker's stomp ssl port.` 
| `${APPLICATION_NAME}-amq-tcp`  |  `61616`  |  `The broker's tcp (openwire) port.` 
| `${APPLICATION_NAME}-amq-tcp-ssl`  |  `61617`  |  `The broker's tcp ssl (openwire) port.` 
|=============

=== Routes

A route is a way to expose a service by giving it an externally-reachable hostname such as `www.example.com`. A defined route and the endpoints
identified by its service can be consumed by a router to provide named connectivity from external clients to your applications. Each route consists
of a route name, service selector, and (optionally) security configuration. Refer to the
https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/routes.html[Openshift documentation] for more information.

|=============
| Service    | Security | Hostname

|=============

=== Build Configurations

A `buildConfig` describes a single build definition and a set of triggers for when a new build should be created.
A `buildConfig` is a REST object, which can be used in a POST to the API server to create a new instance. Refer to
the https://docs.openshift.com/enterprise/3.0/dev_guide/builds.html#defining-a-buildconfig[Openshift documentation]
for more information.

|=============
| STI image  | link | Build output | BuildTriggers and Settings

|=============

=== Deployment Configurations

A deployment in OpenShift is a replication controller based on a user defined template called a deployment configuration. Deployments are created manually or in response to triggered events.
Refer to the https://docs.openshift.com/enterprise/3.0/dev_guide/deployments.html#creating-a-deployment-configuration[Openshift documentation] for more information.

==== Triggers

A trigger drives the creation of new deployments in response to events, both inside and outside OpenShift. Refer to the
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-developer-guide#triggers[Openshift documentation] for more information.

|============
|Deployment | Triggers

| `${APPLICATION_NAME}-amq`  |  `ImageChange` 
|============

==== Replicas

A replication controller ensures that a specified number of pod "replicas" are running at any one time.
If there are too many, the replication controller kills some pods. If there are too few, it starts more.
Refer to the https://cloud.google.com/container-engine/docs/replicationcontrollers/[container-engine documentation]
for more information.

|============
|Deployment | Replicas

| `${APPLICATION_NAME}-amq`  |  `1` 
|============

==== Pod Template

===== Service Accounts

Service accounts are API objects that exist within each project. They can be created or deleted like any other API object. Refer to the
https://docs.openshift.com/enterprise/3.0/dev_guide/service_accounts.html#managing-service-accounts[Openshift documentation] for more
information.

|============
|Deployment | Service Account

| `${APPLICATION_NAME}-amq`  |  `amq-service-account` 
|============

===== Image

|============
|Deployment | Image

| `${APPLICATION_NAME}-amq`  |  `jboss-amq-6` 
|============

===== Readiness Probe


====== ${APPLICATION_NAME}-amq
----
/bin/bash

-c

curl -s -L -u ${AMQ_ADMIN_USERNAME}:${AMQ_ADMIN_PASSWORD} 'http://localhost:8161/hawtio/jolokia/read/org.apache.activemq:type=Broker,brokerName=*,service=Health/CurrentStatus' | grep -q '"CurrentStatus" *: *"Good"'
----


===== Exposed Ports

|=============
|Deployments | Name  | Port  | Protocol

.7+| `${APPLICATION_NAME}-amq`
| `amqp`  |  `5672`  |  `TCP` 
| `amqp-ssl`  |  `5671`  |  `TCP` 
| `mqtt`  |  `1883`  |  `TCP` 
| `stomp`  |  `61613`  |  `TCP` 
| `stomp-ssl`  |  `61612`  |  `TCP` 
| `tcp`  |  `61616`  |  `TCP` 
| `tcp-ssl`  |  `61617`  |  `TCP` 
|=============

===== Image Environment Variables

|=======================================================================
|Deployment |Variable name |Description |Example value

.10+| `${APPLICATION_NAME}-amq`
| `AMQ_USER`  |  `Broker user name`  |  `${MQ_USERNAME}` 
| `AMQ_PASSWORD`  |  `Broker user password`  |  `${MQ_PASSWORD}` 
| `AMQ_PROTOCOLS`  |  `Protocol to configure.  Only openwire is supported by EAP.  amqp, amqp+ssl, mqtt, stomp, stomp+ssl, and ssl are not supported by EAP`  |  `${MQ_PROTOCOL}` 
| `AMQ_QUEUES`  |  `Queue names`  |  `${MQ_QUEUES}` 
| `AMQ_TOPICS`  |  `Topic names`  |  `${MQ_TOPICS}` 
| `AMQ_ADMIN_USERNAME`  |  `ActiveMQ Admin User`  |  `${AMQ_ADMIN_USERNAME}` 
| `AMQ_ADMIN_PASSWORD`  |  `ActiveMQ Admin Password`  |  `${AMQ_ADMIN_PASSWORD}` 
| `AMQ_KEYSTORE_TRUSTSTORE_DIR`  |  `SSL key store filename`  |  `/etc/amq-secret-volume` 
| `AMQ_TRUSTSTORE`  |  `SSL trust store filename`  |  `${AMQ_TRUSTSTORE}` 
| `AMQ_KEYSTORE`  |  `SSL key store filename`  |  `${AMQ_KEYSTORE}` 
|=======================================================================

=====  Volumes

|=============
|Deployment |Name  | mountPath | Purpose | readOnly 

| `${APPLICATION_NAME}-amq`  |  `broker-secret-volume`  |  `/etc/amq-secret-volume`  |  `ssl certs`  |  `True` 
|=============

=== External Dependencies

==== Volume Claims

A `PersistentVolume` object is a storage resource in an OpenShift cluster. Storage is provisioned by an administrator
by creating `PersistentVolume` objects from sources such as GCE Persistent Disks, AWS Elastic Block Stores (EBS), and NFS mounts.
Refer to the https://docs.openshift.com/enterprise/3.0/dev_guide/persistent_volumes.html#overview[Openshift documentation] for
more information.

|=============
|Name | Access Mode

| `${APPLICATION_NAME}-amq-claim`  |  `ReadWriteOnce` 
|=============

==== Secrets 

This template requires https://github.com/jboss-openshift/application-templates/blob/master/secrets/amq-app-secrets.json[amq-app-secrets.json] to be installed for the application to run.
